### ISSUE TITLE
Release needed

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Framework#54]
The version 1 have been broken for quite some time even after the merge on https://github.com/auraphp/Aura.Framework/pull/52 . 

It will be nice if a release is made for the same for if some tries let them see a Hello World .

**Comment by pmjones** [comment]
Well, it took a while to remember how I used to do it, but it's done. Aura.Framework, Aura.Framework_Demo, and system now all have 1.0.1 releases.

**Comment by harikt** [comment]
> Well, it took a while to remember how I used to do it

I did forget things that are done recently. So I don't blame you :) .

> but it's done.

Thank you.
